"""
    API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 2.8.34
    Generated by: https://openapi-generator.tech
"""


import unittest

import semaphore_client
from semaphore_client.api.projects_api import ProjectsApi  # noqa: E501


class TestProjectsApi(unittest.TestCase):
    """ProjectsApi unit test stubs"""

    def setUp(self):
        self.api = ProjectsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_projects_get(self):
        """Test case for projects_get

        Get projects  # noqa: E501
        """
        pass

    def test_projects_post(self):
        """Test case for projects_post

        Create a new project  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
