"""
    API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 2.8.34
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import semaphore_client
from semaphore_client.model.project_project_id_users_get_request import ProjectProjectIdUsersGetRequest


class TestProjectProjectIdUsersGetRequest(unittest.TestCase):
    """ProjectProjectIdUsersGetRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProjectProjectIdUsersGetRequest(self):
        """Test ProjectProjectIdUsersGetRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ProjectProjectIdUsersGetRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
