"""
    API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 2.8.34
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import semaphore_client
from semaphore_client.model.access_key_request import AccessKeyRequest


class TestAccessKeyRequest(unittest.TestCase):
    """AccessKeyRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAccessKeyRequest(self):
        """Test AccessKeyRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AccessKeyRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
