"""
    API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 2.8.34
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import semaphore_client
from semaphore_client.model.inventory_request import InventoryRequest


class TestInventoryRequest(unittest.TestCase):
    """InventoryRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInventoryRequest(self):
        """Test InventoryRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InventoryRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
