"""
    API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 2.8.34
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import semaphore_client
from semaphore_client.model.project_project_id_tasks_get_request import ProjectProjectIdTasksGetRequest


class TestProjectProjectIdTasksGetRequest(unittest.TestCase):
    """ProjectProjectIdTasksGetRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProjectProjectIdTasksGetRequest(self):
        """Test ProjectProjectIdTasksGetRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ProjectProjectIdTasksGetRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
