"""
    API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 2.8.34
    Generated by: https://openapi-generator.tech
"""


import unittest

import semaphore_client
from semaphore_client.api.schedule_api import ScheduleApi  # noqa: E501


class TestScheduleApi(unittest.TestCase):
    """ScheduleApi unit test stubs"""

    def setUp(self):
        self.api = ScheduleApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_project_project_id_schedules_post(self):
        """Test case for project_project_id_schedules_post

        create schedule  # noqa: E501
        """
        pass

    def test_project_project_id_schedules_schedule_id_delete(self):
        """Test case for project_project_id_schedules_schedule_id_delete

        Deletes schedule  # noqa: E501
        """
        pass

    def test_project_project_id_schedules_schedule_id_get(self):
        """Test case for project_project_id_schedules_schedule_id_get

        Get schedule  # noqa: E501
        """
        pass

    def test_project_project_id_schedules_schedule_id_put(self):
        """Test case for project_project_id_schedules_schedule_id_put

        Updates schedule  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
