# flake8: noqa

"""
    API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 2.8.34
    Generated by: https://openapi-generator.tech
"""


__version__ = "1.0.0"

# import ApiClient
from semaphore_client.api_client import ApiClient

# import Configuration
from semaphore_client.configuration import Configuration

# import exceptions
from semaphore_client.exceptions import OpenApiException
from semaphore_client.exceptions import ApiAttributeError
from semaphore_client.exceptions import ApiTypeError
from semaphore_client.exceptions import ApiValueError
from semaphore_client.exceptions import ApiKeyError
from semaphore_client.exceptions import ApiException
